[package]
name = "variables_mutability"
version = "0.1.0"
authors = ["Indra Gunawan <i.gunawan@whim.sg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
